obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.53, 0.38], [0.53, -0.38], [-0.53, 0.38], [-0.53, -0.38]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: velodyne, data_type: PointCloud2, topic: velodyne_points, marking: true, clearing: true, max_obstacle_height: 1.5, min_obstacle_height: 0.25}
