obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.53, 0.38], [-0.53, 0.38], [-0.53, -0.38], [0.53, -0.38]]
robot_radius: 0.8
inflation_radius: 1.2

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: velodyne, data_type: PointCloud2, topic: velodyne_points, marking: true, clearing: true, max_obstacle_height: 1.5, min_obstacle_height: 0.15}

inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.3  # max. distance from an obstacle at which costs are incurred for planning paths. 

obstacles:
  publish_voxel_map:    true