global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1
  static_map: true

  inflation_layer:
    inflate_unknown: true

  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}