local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 4
  height: 4
  resolution: 0.05

  plugins:
   - {name: voxel_layer,     type: "rtabmap_ros::VoxelLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  voxel_layer:
    enabled: true
    publish_voxel_map: true
    observation_sources: 3d_cloud
    3d_cloud:
      data_type: PointCloud2
      topic: /velodyne_points
      marking: true
      clearing: true
      min_obstacle_height: -1000
      max_obstacle_height: 1000
    z_voxels: 9
    z_resolution: 0.05
    footprint_clearing_enabled: false